### ISSUE TITLE
Complete section 4. Domain models

### ISSUE THREAD

**Issue by yulia99** [yulia99/soen343_Team-Rocket_2022#10]
Create a domain model which represents the description logic of the project.

**Comment by melisa1026** [comment]
First draft of domain models: ![17048638-A083-4E56-AF93-1DD990E2A612](https://user-images.githubusercontent.com/68923209/191130035-7dea3f3d-ee1b-46c2-a8e9-9d5cc726bef5.png)

**Comment by dzm-fiodarau** [comment]
As we discussed it in the meeting, follows an improved domain model:

![image](https://user-images.githubusercontent.com/78175065/191137309-c59dd237-fac1-474c-a34c-f07b70d88775.png)
