### ISSUE TITLE
Complete section 3. Context diagram

### ISSUE THREAD

**Issue by yulia99** [yulia99/soen343_Team-Rocket_2022#9]
Create a context diagram that would illustrate external entities that will interact with the community services platform.

**Comment by dzm-fiodarau** [comment]
The following context diagram shows external entities that will interact with our sport-oriented community services platform. It also indicates what sort of interactions will happen between these entities and our system.

![image](https://user-images.githubusercontent.com/78175065/191137487-ad051d6b-9180-4b05-be8a-c1c943fd83a9.png)
